apiVersion: v1
kind: ConfigMap

metadata:
  name: aerocompliance-pro-config

data:
  POSTGRES_DB: "aerocompliance"
  POSTGRES_USER: "aerocompliance"
  POSTGRES_HOST: "aerocompliance-pro-postgres"
  POSTGRES_PORT: "5432"

  REDIS_URL: "redis://aerocompliance-pro-redis:6379/0"
