apiVersion: v1
kind: Secret

metadata:
  name: aerocompliance-pro-secrets

type: Opaque

stringData:
  DJANGO_SECRET_KEY: "django-insecure-he#&#$n_ej7f3+6&0fg&_k44dh4*q$a2y5qvjilb-#u%(_oslz"
  POSTGRES_PASSWORD: "aerocompliance"
