# Generated by Django 6.0.5 on 2026-05-07 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0001_initial'),
        ('aircraft', '0001_initial'),
        ('amp', '0001_initial'),
        ('mel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('CRS', 'Certificate of Release to Service'), ('WORK_ORDER', 'Work Order'), ('INSPECTION', 'Inspection Report'), ('AD_EVIDENCE', 'AD Compliance Evidence'), ('MEL_EVIDENCE', 'MEL Evidence'), ('AMP_EVIDENCE', 'AMP Evidence')], max_length=30)),
                ('file', models.FileField(upload_to='aircraft_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='aircraft.aircraft')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.airworthinessdirective')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='records.document')),
                ('maintenance_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amp.maintenancetask')),
                ('mel_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mel.melitem')),
            ],
        ),
    ]
