# Generated by Django 6.0.5 on 2026-05-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aircraft", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amp_status", models.CharField(max_length=20)),
                ("mel_status", models.CharField(max_length=20)),
                ("ad_status", models.CharField(max_length=20)),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("AIRWORTHY", "Airworthy"),
                            ("RESTRICTED", "Restricted"),
                            ("UNFIT", "Unfit"),
                        ],
                        default="AIRWORTHY",
                        max_length=20,
                    ),
                ),
                ("last_evaluated", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_snapshot",
                        to="aircraft.aircraft",
                    ),
                ),
            ],
        ),
    ]
